### ISSUE TITLE
Logo

### ISSUE THREAD

**Issue by ml31415** [limx0/betfair_parser#18]
For documentation and the github-pages, I guess a little logo couldn't hurt. I fed some prompts into https://huggingface.co/spaces/DeepFloyd/IF , maybe you like one of it.

![bfp5](https://github.com/limx0/betfair_parser/assets/2386612/94cb342a-0fa0-4a41-8432-f27ff2ce76fc)
![bfp4](https://github.com/limx0/betfair_parser/assets/2386612/7b5496f3-6950-4cab-9b83-9f802331968c)
![bfp3](https://github.com/limx0/betfair_parser/assets/2386612/b6b83e85-2791-48f2-b954-211b3716c143)
![bfp2](https://github.com/limx0/betfair_parser/assets/2386612/5a3abd2b-e903-4c5a-aac2-9203485e58c6)
![bfp1](https://github.com/limx0/betfair_parser/assets/2386612/ddd0736a-06dc-4727-a20d-8f6634cdd26e)

**Comment by limx0** [comment]
Ha, yep I'm not against it at all. Number 2 probably my pick from the above, but no strong preferences. 

Any stand out to you?

**Comment by ml31415** [comment]
Fine with anything. Let's take 2 then.

**Comment by ml31415** [comment]
My incompetent attempt on cutting out and vectorizing the logo.

[bfp.pdf](https://github.com/limx0/betfair_parser/files/11592110/bfp.pdf)
![bfp](https://github.com/limx0/betfair_parser/assets/2386612/819763ee-1977-4322-815a-899dd246478f)
![bfp](https://github.com/limx0/betfair_parser/assets/2386612/1567702a-c0e6-4f30-9635-6833d5deafbd)

**Comment by ml31415** [comment]
Two more.
![logo_1](https://github.com/limx0/betfair_parser/assets/2386612/10d602a6-627c-48f1-8145-2f14232a8320)
![logo_2](https://github.com/limx0/betfair_parser/assets/2386612/5f5ef45a-6788-42dd-a2f5-5fd594c4962f)

**Comment by limx0** [comment]
Top one on the last post is probably my fav - thoughts?

**Comment by ml31415** [comment]
Yeah, mine too. It's the one contained in the PR.
