### ISSUE TITLE
Stricter validation

### ISSUE THREAD

**Issue by ml31415** [limx0/betfair_parser#25]
There are many attributes in the API, that would benefit from stricter validation. E.g. country codes all across the API and many things in RunnerMetaData, age and year entries. That boils down to validating membership of an enum instead of having a `str` or setting a strict range for numerical values.

Now, while it would be possible to implement the stricter validation with the current `msgspec` version, it's unfortunately not possible to configure a different error behaviour, in case some data decoding fails the validation. Already in our small selection of sample data, we have cases, when e.g. country codes are populated with garbage data. Parsing such structures would lead to the parser randomly throwing exceptions, instead of replacing the invalid values with sane default values.

There is not that much, that could be done from our side, except living with "only typechecks" instead of proper sanity checks of the data or implement some "second pass" validation. Both options aren't ideal.

An [issue at `msgspec` is pending](https://github.com/jcrist/msgspec/issues/425), maybe we can rediscuss this and find a good solution.

**Comment by ml31415** [comment]
To document some examples:
- Missing `RunnerMetaData.weight` is (occasionally) marked as `-99`, should be translated to `None`. Better: A positive value should be enforced
- Missing `RunnerMetaData.stall_draw` is (occasionally) marked as `99`, should be translated to `None`. Better: range 1-50 should be enforced
- Missing `RunnerMetaData.sire_year_born` etc. are marked as `0`, should be translated to `None`. Better: range 1950-current year should be enforced
- `RunnerMetaData.cloth_number` should be enforced 1-50
- `RunnerMetaData.age` should be enforced 1-30

**Comment by ml31415** [comment]
`msgspec` now features a new `__post_init__` hook. This might be used for further validation of the data discussed above.
https://github.com/jcrist/msgspec/pull/470

**Comment by ml31415** [comment]
Something like that for `RunnerMetaData` is what I'd imagine. Unfortunately this doesn't work with frozen objects. Looks like we still need to wait for better validation options in `msgspec`

```python
    def __post_init__(self):
        if self.weight_value is not None and self.weight_value <= 0:
            self.weight = None
        if self.stall_draw is not None and self.stall_draw > 50:
            self.stall_draw = None
        if self.sire_year_born is not None and self.sire_year_born < 1980:
            self.sire_year_born = None
        if self.dam_year_born is not None and self.dam_year_born < 1980:
            self.dam_year_born = None
        if self.damsire_year_born is not None and  self.damsire_year_born < 1960:
            self.damsire_year_born = None
        if self.cloth_number is not None and not 0 < self.cloth_number < 50:
            self.cloth_number = None
        if self.age is not None and not 1 < self.age < 30:
            self.age = None
```

```
E           AttributeError: immutable type: 'RunnerMetaData'
```

**Comment by limx0** [comment]
I wonder if we need that to be frozen? I like your validation - maybe we could remove it for this class only and define our own `__hash__` ?

**Comment by limx0** [comment]
https://github.com/limx0/betfair_parser/pull/48

Tests passing and mypy happy - thoughts?

**Comment by ml31415** [comment]
I'd leave it for consistency. There are still some discussions at msgspec going on for better validation, see https://github.com/jcrist/msgspec/issues/483 . We waited long enough, I guess we can wait for a proper solution :p
