### ISSUE TITLE
GetAccountDetails endpoint broken

### ISSUE THREAD

**Issue by limx0** [limx0/betfair_parser#27]
Calling `GetAccountDetails` is currently throwing a `AccountAPINGException: METHOD_NOT_FOUND: Method not found`. 

Repro: 

```python

import requests

from betfair_parser.client import request, login
from betfair_parser.endpoints import ENDPOINTS as endpoints
from betfair_parser.spec.accounts.operations import GetAccountDetails

session = requests.Session()
login(session, "xxx", "xxx", "xxx")

# Throws
resp = request(
    session,
    GetAccountDetails(),
    endpoints=endpoints,
)


```

**Comment by ml31415** [comment]
Yeah, that should ber GetAccountDetails.with_params(), but that currently also fails. `__init__` can't be defined on `Struct`s, but we need to fill out `method` and `id. Should we rename `with_params()`, as it's a kind of mandatory constructor?

**Comment by limx0** [comment]
> Should we rename with_params(), as it's a kind of mandatory constructor?

Yeah, no strong opinions here; happy to leave it as is for now.

**Comment by ml31415** [comment]
I'll put up a reminder for that.
