### ISSUE TITLE
Changed behaviour with msgspec 0.18

### ISSUE THREAD

**Issue by ml31415** [limx0/betfair_parser#33]
Looks like the parsing of `Union[int, str]` was changed, both for strict and non-strict parsing. `msgspec` now doesn't attempt to parse to `int` by default, but instead goes with what it gets. Given the betfair quirks, that means that for all `BetId`, `MatchId`etc. which are defined as such union, now we get str instead of int IDs.

Betfair defines these values as str, but de facto uses ints. I'm a bit unsure, if we should leave it as is or force these values to be int. Both options could be argued. Right now the tests pass, but I had issues with my software running on top of betfair_parser. As a baseline, I guess betfair_parser should provide consistent behaviour independent of any dependency quirks. So that would either mean a version pin or dropping the union instead of a plain int for BetId and MatchId. Or any other option, that I just forgot right now.

**Comment by ml31415** [comment]
Also `customer_ref` checks start to fail, when you put in integer values, which come back as strings.

**Comment by limx0** [comment]
Yep this is a tough one. I'm leaning towards making everything strings for consistency, but my second choice would be ints for `BetId` and `MatchId` and strings for others (given what we know about the data we receive).

Also happy to bump our minimum version to 0.18. 

What do you think?

**Comment by ml31415** [comment]
That's the current `common.type_definitions`:

```python
Date = Annotated[datetime.datetime, msgspec.Meta(title="Date", tz=True)]
SelectionId = Annotated[int, msgspec.Meta(title="SelectionId")]
Venue = Annotated[str, msgspec.Meta(title="Venue")]
MarketId = Annotated[str, msgspec.Meta(title="MarketId")]
Handicap = Annotated[float, msgspec.Meta(title="Handicap")]
EventId = Annotated[str, msgspec.Meta(title="EventId")]
EventTypeId = Annotated[int, msgspec.Meta(title="EventTypeId")]
CountryCode = Annotated[str, msgspec.Meta(title="CountryCode", min_length=2, max_length=3)]
ExchangeId = Annotated[str, msgspec.Meta(title="ExchangeId")]
CompetitionId = Annotated[str, msgspec.Meta(title="CompetitionId")]
Price = Annotated[float, msgspec.Meta(title="Price")]
Size = Annotated[float, msgspec.Meta(title="Size")]
BetId = Annotated[Union[str, int], msgspec.Meta(title="BetId")]
MatchId = Annotated[Union[str, int], msgspec.Meta(title="MatchId")]
CustomerRef = Annotated[Union[str, int], msgspec.Meta(title="CustomerRef")]
CustomerOrderRef = Annotated[Union[str, int], msgspec.Meta(title="CustomerOrderRef")]
CustomerStrategyRef = Annotated[Union[str, int], msgspec.Meta(title="CustomerStrategyRef")]
```
If we're really forced to decide for `int` or `str` exclusively: CustomerRef, CustomerStrategyRef and MarketId must be `str`, as they're forced to be able to contain strings. With the others, I'd tend to go for int, as that's what they're currently used, as already done with SelectionId or EventTypeId.

We might also try to experiment with the [new `__post_init__` method](https://github.com/jcrist/msgspec/pull/470) and try to achieve the previous behaviour. Not sure how well this goes or how much performance it costs.

**Comment by limx0** [comment]
Yep, agreed. I'm happy for:
CustomerRef, CustomerStrategyRef and MarketId -> str
BetId, MatchId ->int
