### ISSUE TITLE
ocm.con and mcm.market_definition

### ISSUE THREAD

**Issue by ml31415** [limx0/betfair_parser#39]
There are currently those two definitions for `OCM.con` and for `MCM.market_definition` in the API implementation. They're also tested against two JSON files. Nevertheless, those two definitions don't show up in the Betfair API definition and also not in any data I got from live sources so far.

@limx0 Was this data actually found out there in the wild and need some special circumstances to reproduce? Or is this rather some oversight, that should be just removed / fixed?

**Comment by limx0** [comment]
Hey @ml31415, I actually can't remember - it could have been some old format or fields. In any case I think it's fine to remove.

Cheers!
