### ISSUE TITLE
camelCase

### ISSUE THREAD

**Issue by ml31415** [limx0/betfair_parser#6]
Hi Brad,

looking through the codebase, the naming of anything within `spec` follows closely the betfair naming convention of using camel case. This rather unpythonic syntax might get thrown out by using `rename="camel"` within the `BaseMessage` definition. This would leave the translation of all the fieldnames into camelcase and back to `msgspec`, and the public API would be nice and shiny pythonic.

Now, this is a breaking API change. Though as it seems there aren't too many users so far, I guess it might be worth it to switch, better earlier than later.

**Comment by limx0** [comment]
Hey Michael,

Good pick up. +1, I don't think there are many users so happy to make this change. Would you like to PR something? Otherwise I can pick this up in the next couple of days.

**Comment by ml31415** [comment]
I'll add it soon. Just wanted to make sure you're fine with it before introducing that breaking changes.
