### ISSUE TITLE
datetime handling

### ISSUE THREAD

**Issue by ml31415** [limx0/betfair_parser#7]
Currently the datetime handling is inconsistent throughout the API. Some parts leave it as plain string, while e.g. navigation converts it into datetime without timezone.

Both is imho not optimal. Converting to datetime as in navigation does not preserve the timezone information. That might lead to issues. I darkly remember running into issues myself with that, when the API was returning different localized dates depending on locale settings etc.

Leaving it as string unparsed also leaves too much room for errors later on for my taste.

Personally I'd favor to convert anything that's a time into a unix timestamp /  seconds since epoch or at least a timezone aware datetime. What's your opinion?

**Comment by limx0** [comment]
Yep :100: on converting everything to UTC datetimes. 

Anything that's not consistent is likely just things I'm not using - please feel free to call out anything and happy to fix.

**Comment by ml31415** [comment]
Date is now consistently defined as datetime object with timezone required. Fixed somewhen along the last some commits.

`Date = Annotated[datetime.datetime, msgspec.Meta(title="Date", tz=True)]`
